repos:
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Prevent giant files from being committed.
      - id: check-added-large-files
        exclude: .devops/
        args:
          - --maxkb=20480
      # Simply check whether files parse as valid python.
      - id: check-ast
      # Require literal syntax when initializing empty or zero Python builtin types.
      - id: check-builtin-literals
      # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-case-conflict
      # Checks for a common error of placing code before the docstring.
      - id: check-docstring-first
      # Checks that non-binary executables have a proper shebang.
      - id: check-executables-have-shebangs
      # Attempts to load all json files to verify syntax.
      - id: check-json
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Attempts to load all yaml files to verify syntax.
      - id: check-yaml
      # Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: debug-statements
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
        exclude: .devops/
      # Checks for the existence of private keys.
      - id: detect-private-key
      #  # This hook replaces double quoted strings with single quoted strings.
      #  - id: double-quote-string-fixer
      # removes UTF-8 byte order marker
      - id: fix-byte-order-marker
      # To remove the coding pragma pass (# -*- coding: utf-8 -*-) --remove (useful in a python3-only codebase)
      - id: fix-encoding-pragma
        args:
          - --remove
      # Prevent addition of new git submodules.
      - id: forbid-new-submodules
      # Assert that files in tests/ end in _test.py.
      - id: name-tests-test
      # Checks that all your JSON files are pretty.
      - id: pretty-format-json
        exclude: .devops/
        args:
          - --autofix
          - --no-sort-keys
          - --indent=4
          - --no-ensure-ascii
      # Sorts entries in requirements.txt and removes incorrect entry for pkg-resources==0.0.0.
      - id: requirements-txt-fixer
      # Trims trailing whitespace.
      - id: trailing-whitespace
        exclude: .devops/
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          # DTZ
          - flake8-datetimez
          # Y
          - flake8-pyi
          # Q
          # - flake8-quotes
          # R
          - flake8-return
          # STR
          # - flake8-strings
          # TYP
          - flake8-typing-imports
          # T
          - flake8-tuple
          # N
          - pep8-naming
        args:
          - --count
          # 不检查前端内容
          - --exclude=.devops/
          - --max-complexity=10
          # 与Black兼容的行宽与规则设置
          - --ignore=E203,E501,W503,TYP001
          - --max-line-length=88
          - --select=B,C,D,E,F,N,R,S,T,W,Y
          # 其它
          - --show-source
          - --statistics
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-requests
          - tokenize-rt
          - types-redis
          - types-pytz
        args:
          - --install-types
          - --ignore-missing-imports
          - --follow-imports=skip
          - --strict-optional
